---
- name: copy hosts
  copy: src="./files/hosts" dest="/etc/hosts" force=yes

- name: create  group
  group: name={{ group }} state=present

- name: create user
  user: name={{ user }} createhome=yes generate_ssh_key=no  password={{ password }} groups={{ group }} append=yes

- name: install software
  apt: name=unzip state=present
  apt: name=supervisor state=present

- name: install openssh-server
  apt: name=openssh-server state=present
