---
- stat: path=/swapfile
  register: swapfile
- name: create swap
  shell: "sudo fallocate -l 4G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile"
  when: swapfile.stat.exists == False
